/**
 * Users Module Error Codes
 * Pattern: USERS_<RESOURCE>_<ERROR_TYPE>_<NUMBER>
 */
export enum UserErrorCode {
  // User Not Found
  USERS_USER_NOT_FOUND_001 = 'USERS_USER_NOT_FOUND_001',

  // User Validation Errors
  USERS_USER_INVALID_EMAIL_001 = 'USERS_USER_INVALID_EMAIL_001',
  USERS_USER_INVALID_PASSWORD_002 = 'USERS_USER_INVALID_PASSWORD_002',
  USERS_USER_INVALID_DATA_003 = 'USERS_USER_INVALID_DATA_003',

  // User Already Exists
  USERS_USER_ALREADY_EXISTS_001 = 'USERS_USER_ALREADY_EXISTS_001',

  // User Creation Errors
  USERS_USER_CREATION_FAILED_001 = 'USERS_USER_CREATION_FAILED_001',

  // User Update Errors
  USERS_USER_UPDATE_FAILED_001 = 'USERS_USER_UPDATE_FAILED_001',

  // User Delete Errors
  USERS_USER_DELETE_FAILED_001 = 'USERS_USER_DELETE_FAILED_001',
}
