/**
 * Core Error Codes
 * Pattern: CORE_<RESOURCE>_<ERROR_TYPE>_<NUMBER>
 */
export enum CoreErrorCode {
  // Value Object Errors
  CORE_VALUE_INVALID_001 = 'CORE_VALUE_INVALID_001',
  CORE_VALUE_REQUIRED_002 = 'CORE_VALUE_REQUIRED_002',

  // UUID Errors
  CORE_UUID_INVALID_001 = 'CORE_UUID_INVALID_001',
  CORE_UUID_MALFORMED_002 = 'CORE_UUID_MALFORMED_002',

  // Authentication/Authorization Errors (General)
  CORE_AUTH_UNAUTHORIZED_001 = 'CORE_AUTH_UNAUTHORIZED_001',
  CORE_AUTH_FORBIDDEN_002 = 'CORE_AUTH_FORBIDDEN_002',
  CORE_AUTH_TOKEN_MISSING_003 = 'CORE_AUTH_TOKEN_MISSING_003',
  CORE_AUTH_TOKEN_INVALID_004 = 'CORE_AUTH_TOKEN_INVALID_004',

  // Generic Domain Errors
  CORE_DOMAIN_NOT_FOUND_001 = 'CORE_DOMAIN_NOT_FOUND_001',
  CORE_DOMAIN_CONFLICT_002 = 'CORE_DOMAIN_CONFLICT_002',
  CORE_DOMAIN_BAD_REQUEST_003 = 'CORE_DOMAIN_BAD_REQUEST_003',

  // Infrastructure Errors
  CORE_INFRA_DATABASE_001 = 'CORE_INFRA_DATABASE_001',
  CORE_INFRA_NETWORK_002 = 'CORE_INFRA_NETWORK_002',
  CORE_INFRA_EXTERNAL_SERVICE_003 = 'CORE_INFRA_EXTERNAL_SERVICE_003',
  CORE_INFRA_INTERNAL_ERROR_004 = 'CORE_INFRA_INTERNAL_ERROR_004',
}
