/**
 * Auth Module Error Codes
 * Pattern: AUTH_<RESOURCE>_<ERROR_TYPE>_<NUMBER>
 */
export enum AuthErrorCode {
  // Credentials Errors
  AUTH_CREDENTIALS_INVALID_001 = 'AUTH_CREDENTIALS_INVALID_001',
  AUTH_CREDENTIALS_MISSING_002 = 'AUTH_CREDENTIALS_MISSING_002',

  // User Registration Errors
  AUTH_USER_ALREADY_REGISTERED_001 = 'AUTH_USER_ALREADY_REGISTERED_001',
  AUTH_USER_ALREADY_CONFIRMED_002 = 'AUTH_USER_ALREADY_CONFIRMED_002',
  AUTH_USER_NOT_CONFIRMED_003 = 'AUTH_USER_NOT_CONFIRMED_003',
  AUTH_USER_NOT_FOUND_004 = 'AUTH_USER_NOT_FOUND_004',

  // Token Errors
  AUTH_TOKEN_INVALID_001 = 'AUTH_TOKEN_INVALID_001',
  AUTH_TOKEN_EXPIRED_002 = 'AUTH_TOKEN_EXPIRED_002',
  AUTH_TOKEN_MISSING_003 = 'AUTH_TOKEN_MISSING_003',
  AUTH_TOKEN_SUBJECT_MISMATCH_004 = 'AUTH_TOKEN_SUBJECT_MISMATCH_004',

  // Role/Permission Errors
  AUTH_ROLE_NOT_FOUND_001 = 'AUTH_ROLE_NOT_FOUND_001',
  AUTH_ROLE_NOT_ASSIGNED_002 = 'AUTH_ROLE_NOT_ASSIGNED_002',
  AUTH_PERMISSION_NOT_FOUND_001 = 'AUTH_PERMISSION_NOT_FOUND_001',
  AUTH_PERMISSION_DENIED_002 = 'AUTH_PERMISSION_DENIED_002',
  AUTH_PERMISSION_INSUFFICIENT_003 = 'AUTH_PERMISSION_INSUFFICIENT_003',
  AUTH_ROLE_PERMISSION_NOT_FOUND_001 = 'AUTH_ROLE_PERMISSION_NOT_FOUND_001',

  // Cognito Errors
  AUTH_COGNITO_USER_MISSING_001 = 'AUTH_COGNITO_USER_MISSING_001',
  AUTH_COGNITO_REGISTRATION_FAILED_002 = 'AUTH_COGNITO_REGISTRATION_FAILED_002',
}
